version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./tmp/mongo:/data/db
    restart: always

  mongo-seed:
    image: mongo-seed
    build: 
      context: ./gateway.api/db-seed
      dockerfile: Dockerfile

  gateway.api:
    image: gateway.api
    build:
      context: ./gateway.api
      dockerfile: Dockerfile-dev
    container_name: gateway.api
    volumes:
      - ./tmp/npm:/root/.npm:z
      - ./gateway.api/src:/usr/src/app/src:z
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DBHOST=mongodb://mongo:27017
    depends_on:
      - mongo
    restart: always
  